name: Feature request
description: Suggest an enhancement.
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the use case rather than the implementation.
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed behaviour
      description: How would you like this to work?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
